# Generated by Django 5.2.3 on 2025-06-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='createAt',
            new_name='createdAt',
        ),
    ]
